// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4mA1sKcxElSaMf4YpNSAUz2EFEmWo-KQ',
    appId: '1:966628445351:web:5158ffd987b880c4a01f82',
    messagingSenderId: '966628445351',
    projectId: 'prueba-flutter-a14dd',
    authDomain: 'prueba-flutter-a14dd.firebaseapp.com',
    storageBucket: 'prueba-flutter-a14dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDundZ2FLLpd9UKfUN4AIenkscC-MIj16c',
    appId: '1:966628445351:android:7193682a78c01f76a01f82',
    messagingSenderId: '966628445351',
    projectId: 'prueba-flutter-a14dd',
    storageBucket: 'prueba-flutter-a14dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDozayoWaloHb7SnT--5TTpt1SWdGTAkX0',
    appId: '1:966628445351:ios:8ee84b350f85ec17a01f82',
    messagingSenderId: '966628445351',
    projectId: 'prueba-flutter-a14dd',
    storageBucket: 'prueba-flutter-a14dd.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDozayoWaloHb7SnT--5TTpt1SWdGTAkX0',
    appId: '1:966628445351:ios:8ee84b350f85ec17a01f82',
    messagingSenderId: '966628445351',
    projectId: 'prueba-flutter-a14dd',
    storageBucket: 'prueba-flutter-a14dd.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4mA1sKcxElSaMf4YpNSAUz2EFEmWo-KQ',
    appId: '1:966628445351:web:60029b2b77586925a01f82',
    messagingSenderId: '966628445351',
    projectId: 'prueba-flutter-a14dd',
    authDomain: 'prueba-flutter-a14dd.firebaseapp.com',
    storageBucket: 'prueba-flutter-a14dd.appspot.com',
  );
}
